name: Test workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          lein: 2.9.1
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: lein test
